### ISSUE TITLE
Tracking issue for Ember v4.0 compatibility

### ISSUE THREAD

**Issue by raido** [ember-cli/ember-page-title#222]
Getting back on track plan for Ember v4.0 (lifted from here -> https://github.com/ember-cli/ember-page-title/pull/217#issuecomment-950388942):

Tier 1:

- [x] Ember v3.28 upgrade, get builds greenish as beta scenario is allowed to fail -> #217 
- [x] Cherry pick or ask author to only do assign related changes in this PR - #218
- [x] ember-auto-import 2.x upgrade #223
- [x] Release a major version v7.x, because PR #217 dropped Node 10 support 
- [x] Get ember-page-title updated to v7.x for cli blueprints. -> https://github.com/ember-cli/ember-cli/pull/9679

~Tier 2:~

~- [ ] ember-auto-import 2.x upgrade~
~- [ ] Release another major version~

**Comment by raido** [comment]
This is completed as of today.
